package com.civicforge.challenges.domain;

public enum ChallengeAction {
    SUBMIT, START_REVIEW, REQUEST_CLARIFICATION, RESUBMIT, VERIFY, REJECT,
    CLASSIFY, PRIORITIZE, ROUTE, PUBLISH, EXPRESS_INTEREST, ACCEPT,
    FORM_PROJECT, START_PROGRESS, BEGIN_PILOT, DEPLOY, MEASURE_IMPACT, CLOSE, ARCHIVE
}
