package com.civicforge.challenges.domain;

public enum ChallengeStatus {
    DRAFT, SUBMITTED, UNDER_REVIEW, CLARIFICATION_REQUIRED, VERIFIED, REJECTED,
    CLASSIFIED, PRIORITIZED, ROUTED, PUBLISHED, INTERESTED, ACCEPTED,
    PROJECT_FORMED, IN_PROGRESS, PILOT, DEPLOYED, IMPACT_MEASURED, CLOSED, ARCHIVED
}
