package com.civicforge.common.exception;

public interface ErrorCode {
    String VALIDATION_ERROR = "VALIDATION_ERROR";
    String UNAUTHORIZED = "UNAUTHORIZED";
    String FORBIDDEN = "FORBIDDEN";
    String NOT_FOUND = "NOT_FOUND";
    String CONFLICT = "CONFLICT";
    String INVALID_STATE = "INVALID_STATE";
    String RATE_LIMITED = "RATE_LIMITED";
    String DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE";
    String INTERNAL_ERROR = "INTERNAL_ERROR";
    String CHALLENGE_NOT_FOUND = "CHALLENGE_NOT_FOUND";
    String CHALLENGE_INVALID_STATE = "CHALLENGE_INVALID_STATE";
    String CHALLENGE_INVALID_TRANSITION = "CHALLENGE_INVALID_TRANSITION";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
    String INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
    String ORG_NOT_FOUND = "ORG_NOT_FOUND";
    String ORG_ACCESS_DENIED = "ORG_ACCESS_DENIED";
    String FILE_TOO_LARGE = "FILE_TOO_LARGE";
    String FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED";
    String BULK_JOB_NOT_FOUND = "BULK_JOB_NOT_FOUND";
    String BULK_PERMISSION_DENIED = "BULK_PERMISSION_DENIED";
    String AI_SERVICE_UNAVAILABLE = "AI_SERVICE_UNAVAILABLE";
    String CHALLENGE_ACCESS_DENIED = "CHALLENGE_ACCESS_DENIED";
    String FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED";
}